import { ICountry } from '../../app/core/models/projects.model';

export const enCountries: ICountry[] = [
{ iso3166CountryCode: "AF", name: "Afghanistan" },
{ iso3166CountryCode: "AX", name: "\u00c5land Islands" },
{ iso3166CountryCode: "AL", name: "Albania" },
{ iso3166CountryCode: "DZ", name: "Algeria" },
{ iso3166CountryCode: "AS", name: "American Samoa" },
{ iso3166CountryCode: "AD", name: "Andorra" },
{ iso3166CountryCode: "AO", name: "Angola" },
{ iso3166CountryCode: "AI", name: "Anguilla" },
{ iso3166CountryCode: "AQ", name: "Antarctica" },
{ iso3166CountryCode: "AG", name: "Antigua & Barbuda" },
{ iso3166CountryCode: "AR", name: "Argentina" },
{ iso3166CountryCode: "AM", name: "Armenia" },
{ iso3166CountryCode: "AW", name: "Aruba" },
{ iso3166CountryCode: "AU", name: "Australia" },
{ iso3166CountryCode: "AT", name: "Austria" },
{ iso3166CountryCode: "AZ", name: "Azerbaijan" },
{ iso3166CountryCode: "BS", name: "Bahamas" },
{ iso3166CountryCode: "BH", name: "Bahrain" },
{ iso3166CountryCode: "BD", name: "Bangladesh" },
{ iso3166CountryCode: "BB", name: "Barbados" },
{ iso3166CountryCode: "BY", name: "Belarus" },
{ iso3166CountryCode: "BE", name: "Belgium" },
{ iso3166CountryCode: "BZ", name: "Belize" },
{ iso3166CountryCode: "BJ", name: "Benin" },
{ iso3166CountryCode: "BM", name: "Bermuda" },
{ iso3166CountryCode: "BT", name: "Bhutan" },
{ iso3166CountryCode: "BO", name: "Bolivia" },
{ iso3166CountryCode: "BA", name: "Bosnia & Herzegovina" },
{ iso3166CountryCode: "BW", name: "Botswana" },
{ iso3166CountryCode: "BV", name: "Bouvet Island" },
{ iso3166CountryCode: "BR", name: "Brazil" },
{ iso3166CountryCode: "IO", name: "British Indian Ocean Territory" },
{ iso3166CountryCode: "VG", name: "British Virgin Islands" },
{ iso3166CountryCode: "BN", name: "Brunei" },
{ iso3166CountryCode: "BG", name: "Bulgaria" },
{ iso3166CountryCode: "BF", name: "Burkina Faso" },
{ iso3166CountryCode: "BI", name: "Burundi" },
{ iso3166CountryCode: "KH", name: "Cambodia" },
{ iso3166CountryCode: "CM", name: "Cameroon" },
{ iso3166CountryCode: "CA", name: "Canada" },
{ iso3166CountryCode: "CV", name: "Cape Verde" },
{ iso3166CountryCode: "BQ", name: "Caribbean Netherlands" },
{ iso3166CountryCode: "KY", name: "Cayman Islands" },
{ iso3166CountryCode: "CF", name: "Central African Republic" },
{ iso3166CountryCode: "TD", name: "Chad" },
{ iso3166CountryCode: "CL", name: "Chile" },
{ iso3166CountryCode: "CN", name: "China" },
{ iso3166CountryCode: "CX", name: "Christmas Island" },
{ iso3166CountryCode: "CC", name: "Cocos (Keeling) Islands" },
{ iso3166CountryCode: "CO", name: "Colombia" },
{ iso3166CountryCode: "KM", name: "Comoros" },
{ iso3166CountryCode: "CG", name: "Congo - Brazzaville" },
{ iso3166CountryCode: "CD", name: "Congo - Kinshasa" },
{ iso3166CountryCode: "CK", name: "Cook Islands" },
{ iso3166CountryCode: "CR", name: "Costa Rica" },
{ iso3166CountryCode: "CI", name: "C\u00f4te d\u2019Ivoire" },
{ iso3166CountryCode: "HR", name: "Croatia" },
{ iso3166CountryCode: "CU", name: "Cuba" },
{ iso3166CountryCode: "CW", name: "Cura\u00e7ao" },
{ iso3166CountryCode: "CY", name: "Cyprus" },
{ iso3166CountryCode: "CZ", name: "Czechia" },
{ iso3166CountryCode: "DK", name: "Denmark" },
{ iso3166CountryCode: "DJ", name: "Djibouti" },
{ iso3166CountryCode: "DM", name: "Dominica" },
{ iso3166CountryCode: "DO", name: "Dominican Republic" },
{ iso3166CountryCode: "EC", name: "Ecuador" },
{ iso3166CountryCode: "EG", name: "Egypt" },
{ iso3166CountryCode: "SV", name: "El Salvador" },
{ iso3166CountryCode: "GQ", name: "Equatorial Guinea" },
{ iso3166CountryCode: "ER", name: "Eritrea" },
{ iso3166CountryCode: "EE", name: "Estonia" },
{ iso3166CountryCode: "SZ", name: "Eswatini" },
{ iso3166CountryCode: "ET", name: "Ethiopia" },
{ iso3166CountryCode: "FK", name: "Falkland Islands" },
{ iso3166CountryCode: "FO", name: "Faroe Islands" },
{ iso3166CountryCode: "FJ", name: "Fiji" },
{ iso3166CountryCode: "FI", name: "Finland" },
{ iso3166CountryCode: "FR", name: "France" },
{ iso3166CountryCode: "GF", name: "French Guiana" },
{ iso3166CountryCode: "PF", name: "French Polynesia" },
{ iso3166CountryCode: "TF", name: "French Southern Territories" },
{ iso3166CountryCode: "GA", name: "Gabon" },
{ iso3166CountryCode: "GM", name: "Gambia" },
{ iso3166CountryCode: "GE", name: "Georgia" },
{ iso3166CountryCode: "DE", name: "Germany" },
{ iso3166CountryCode: "GH", name: "Ghana" },
{ iso3166CountryCode: "GI", name: "Gibraltar" },
{ iso3166CountryCode: "GR", name: "Greece" },
{ iso3166CountryCode: "GL", name: "Greenland" },
{ iso3166CountryCode: "GD", name: "Grenada" },
{ iso3166CountryCode: "GP", name: "Guadeloupe" },
{ iso3166CountryCode: "GU", name: "Guam" },
{ iso3166CountryCode: "GT", name: "Guatemala" },
{ iso3166CountryCode: "GG", name: "Guernsey" },
{ iso3166CountryCode: "GN", name: "Guinea" },
{ iso3166CountryCode: "GW", name: "Guinea-Bissau" },
{ iso3166CountryCode: "GY", name: "Guyana" },
{ iso3166CountryCode: "HT", name: "Haiti" },
{ iso3166CountryCode: "HM", name: "Heard & McDonald Islands" },
{ iso3166CountryCode: "HN", name: "Honduras" },
{ iso3166CountryCode: "HK", name: "Hong Kong SAR China" },
{ iso3166CountryCode: "HU", name: "Hungary" },
{ iso3166CountryCode: "IS", name: "Iceland" },
{ iso3166CountryCode: "IN", name: "India" },
{ iso3166CountryCode: "ID", name: "Indonesia" },
{ iso3166CountryCode: "IR", name: "Iran" },
{ iso3166CountryCode: "IQ", name: "Iraq" },
{ iso3166CountryCode: "IE", name: "Ireland" },
{ iso3166CountryCode: "IM", name: "Isle of Man" },
{ iso3166CountryCode: "IL", name: "Israel" },
{ iso3166CountryCode: "IT", name: "Italy" },
{ iso3166CountryCode: "JM", name: "Jamaica" },
{ iso3166CountryCode: "JP", name: "Japan" },
{ iso3166CountryCode: "JE", name: "Jersey" },
{ iso3166CountryCode: "JO", name: "Jordan" },
{ iso3166CountryCode: "KZ", name: "Kazakhstan" },
{ iso3166CountryCode: "KE", name: "Kenya" },
{ iso3166CountryCode: "KI", name: "Kiribati" },
{ iso3166CountryCode: "KW", name: "Kuwait" },
{ iso3166CountryCode: "KG", name: "Kyrgyzstan" },
{ iso3166CountryCode: "LA", name: "Laos" },
{ iso3166CountryCode: "LV", name: "Latvia" },
{ iso3166CountryCode: "LB", name: "Lebanon" },
{ iso3166CountryCode: "LS", name: "Lesotho" },
{ iso3166CountryCode: "LR", name: "Liberia" },
{ iso3166CountryCode: "LY", name: "Libya" },
{ iso3166CountryCode: "LI", name: "Liechtenstein" },
{ iso3166CountryCode: "LT", name: "Lithuania" },
{ iso3166CountryCode: "LU", name: "Luxembourg" },
{ iso3166CountryCode: "MO", name: "Macao SAR China" },
{ iso3166CountryCode: "MG", name: "Madagascar" },
{ iso3166CountryCode: "MW", name: "Malawi" },
{ iso3166CountryCode: "MY", name: "Malaysia" },
{ iso3166CountryCode: "MV", name: "Maldives" },
{ iso3166CountryCode: "ML", name: "Mali" },
{ iso3166CountryCode: "MT", name: "Malta" },
{ iso3166CountryCode: "MH", name: "Marshall Islands" },
{ iso3166CountryCode: "MQ", name: "Martinique" },
{ iso3166CountryCode: "MR", name: "Mauritania" },
{ iso3166CountryCode: "MU", name: "Mauritius" },
{ iso3166CountryCode: "YT", name: "Mayotte" },
{ iso3166CountryCode: "MX", name: "Mexico" },
{ iso3166CountryCode: "FM", name: "Micronesia" },
{ iso3166CountryCode: "MD", name: "Moldova" },
{ iso3166CountryCode: "MC", name: "Monaco" },
{ iso3166CountryCode: "MN", name: "Mongolia" },
{ iso3166CountryCode: "ME", name: "Montenegro" },
{ iso3166CountryCode: "MS", name: "Montserrat" },
{ iso3166CountryCode: "MA", name: "Morocco" },
{ iso3166CountryCode: "MZ", name: "Mozambique" },
{ iso3166CountryCode: "MM", name: "Myanmar (Burma)" },
{ iso3166CountryCode: "NA", name: "Namibia" },
{ iso3166CountryCode: "NR", name: "Nauru" },
{ iso3166CountryCode: "NP", name: "Nepal" },
{ iso3166CountryCode: "NL", name: "Netherlands" },
{ iso3166CountryCode: "NC", name: "New Caledonia" },
{ iso3166CountryCode: "NZ", name: "New Zealand" },
{ iso3166CountryCode: "NI", name: "Nicaragua" },
{ iso3166CountryCode: "NE", name: "Niger" },
{ iso3166CountryCode: "NG", name: "Nigeria" },
{ iso3166CountryCode: "NU", name: "Niue" },
{ iso3166CountryCode: "NF", name: "Norfolk Island" },
{ iso3166CountryCode: "KP", name: "North Korea" },
{ iso3166CountryCode: "MK", name: "North Macedonia" },
{ iso3166CountryCode: "MP", name: "Northern Mariana Islands" },
{ iso3166CountryCode: "NO", name: "Norway" },
{ iso3166CountryCode: "OM", name: "Oman" },
{ iso3166CountryCode: "PK", name: "Pakistan" },
{ iso3166CountryCode: "PW", name: "Palau" },
{ iso3166CountryCode: "PS", name: "Palestinian Territories" },
{ iso3166CountryCode: "PA", name: "Panama" },
{ iso3166CountryCode: "PG", name: "Papua New Guinea" },
{ iso3166CountryCode: "PY", name: "Paraguay" },
{ iso3166CountryCode: "PE", name: "Peru" },
{ iso3166CountryCode: "PH", name: "Philippines" },
{ iso3166CountryCode: "PN", name: "Pitcairn Islands" },
{ iso3166CountryCode: "PL", name: "Poland" },
{ iso3166CountryCode: "PT", name: "Portugal" },
{ iso3166CountryCode: "PR", name: "Puerto Rico" },
{ iso3166CountryCode: "QA", name: "Qatar" },
{ iso3166CountryCode: "RE", name: "R\u00e9union" },
{ iso3166CountryCode: "RO", name: "Romania" },
{ iso3166CountryCode: "RU", name: "Russia" },
{ iso3166CountryCode: "RW", name: "Rwanda" },
{ iso3166CountryCode: "WS", name: "Samoa" },
{ iso3166CountryCode: "SM", name: "San Marino" },
{ iso3166CountryCode: "ST", name: "S\u00e3o Tom\u00e9 & Pr\u00edncipe" },
{ iso3166CountryCode: "SA", name: "Saudi Arabia" },
{ iso3166CountryCode: "SN", name: "Senegal" },
{ iso3166CountryCode: "RS", name: "Serbia" },
{ iso3166CountryCode: "SC", name: "Seychelles" },
{ iso3166CountryCode: "SL", name: "Sierra Leone" },
{ iso3166CountryCode: "SG", name: "Singapore" },
{ iso3166CountryCode: "SX", name: "Sint Maarten" },
{ iso3166CountryCode: "SK", name: "Slovakia" },
{ iso3166CountryCode: "SI", name: "Slovenia" },
{ iso3166CountryCode: "SB", name: "Solomon Islands" },
{ iso3166CountryCode: "SO", name: "Somalia" },
{ iso3166CountryCode: "ZA", name: "South Africa" },
{ iso3166CountryCode: "GS", name: "South Georgia & South Sandwich Islands" },
{ iso3166CountryCode: "KR", name: "South Korea" },
{ iso3166CountryCode: "SS", name: "South Sudan" },
{ iso3166CountryCode: "ES", name: "Spain" },
{ iso3166CountryCode: "LK", name: "Sri Lanka" },
{ iso3166CountryCode: "BL", name: "St. Barth\u00e9lemy" },
{ iso3166CountryCode: "SH", name: "St. Helena" },
{ iso3166CountryCode: "KN", name: "St. Kitts & Nevis" },
{ iso3166CountryCode: "LC", name: "St. Lucia" },
{ iso3166CountryCode: "MF", name: "St. Martin" },
{ iso3166CountryCode: "PM", name: "St. Pierre & Miquelon" },
{ iso3166CountryCode: "VC", name: "St. Vincent & Grenadines" },
{ iso3166CountryCode: "SD", name: "Sudan" },
{ iso3166CountryCode: "SR", name: "Suriname" },
{ iso3166CountryCode: "SJ", name: "Svalbard & Jan Mayen" },
{ iso3166CountryCode: "SE", name: "Sweden" },
{ iso3166CountryCode: "CH", name: "Switzerland" },
{ iso3166CountryCode: "SY", name: "Syria" },
{ iso3166CountryCode: "TW", name: "Taiwan" },
{ iso3166CountryCode: "TJ", name: "Tajikistan" },
{ iso3166CountryCode: "TZ", name: "Tanzania" },
{ iso3166CountryCode: "TH", name: "Thailand" },
{ iso3166CountryCode: "TL", name: "Timor-Leste" },
{ iso3166CountryCode: "TG", name: "Togo" },
{ iso3166CountryCode: "TK", name: "Tokelau" },
{ iso3166CountryCode: "TO", name: "Tonga" },
{ iso3166CountryCode: "TT", name: "Trinidad & Tobago" },
{ iso3166CountryCode: "TN", name: "Tunisia" },
{ iso3166CountryCode: "TR", name: "Turkey" },
{ iso3166CountryCode: "TM", name: "Turkmenistan" },
{ iso3166CountryCode: "TC", name: "Turks & Caicos Islands" },
{ iso3166CountryCode: "TV", name: "Tuvalu" },
{ iso3166CountryCode: "UM", name: "U.S. Outlying Islands" },
{ iso3166CountryCode: "VI", name: "U.S. Virgin Islands" },
{ iso3166CountryCode: "UG", name: "Uganda" },
{ iso3166CountryCode: "UA", name: "Ukraine" },
{ iso3166CountryCode: "AE", name: "United Arab Emirates" },
{ iso3166CountryCode: "GB", name: "United Kingdom" },
{ iso3166CountryCode: "US", name: "United States" },
{ iso3166CountryCode: "UY", name: "Uruguay" },
{ iso3166CountryCode: "UZ", name: "Uzbekistan" },
{ iso3166CountryCode: "VU", name: "Vanuatu" },
{ iso3166CountryCode: "VA", name: "Vatican City" },
{ iso3166CountryCode: "VE", name: "Venezuela" },
{ iso3166CountryCode: "VN", name: "Vietnam" },
{ iso3166CountryCode: "WF", name: "Wallis & Futuna" },
{ iso3166CountryCode: "EH", name: "Western Sahara" },
{ iso3166CountryCode: "YE", name: "Yemen" },
{ iso3166CountryCode: "ZM", name: "Zambia" },
{ iso3166CountryCode: "ZW", name: "Zimbabwe" }
]
